os: linux
dist: bionic
language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
services:
  - postgresql

env:
  DOCKER_COMPOSE_VERSION: 1.25.4
  HEROKU_REGISTRY_IMAGE: registry.heroku.com/$HEROKU_APP_NAME/web
  DATABASE_TEST_URL: postgresql://postgres@127.0.0.1:5432/users
  FLASK_APP: project/__init__.py
  FLASK_ENV: development
  APP_SETTINGS: project.config.DevelopmentConfig

before_install:
  - python --version

install:
  # reorganize database
  # try to move under a directory
  - if [[ $TRAVIS_BRANCH == "develop" ]] && [[ $TRAVIS_PYTHON_VERSION == "3.8" ]]; then
      chmod +x ./.travis_build.sh;
      ./.travis_build.sh;
    fi
  - pip install -r requirements.txt

before_script:
  - psql -c "CREATE DATABASE users;" -U postgres
  - gunicorn -b 0.0.0.0:5000 manage:app --daemon

script:
  - python -m pytest "project/tests" --cov="project"
  - python -m black project
  - python -m flake8 project
  - python -m isort project/**/*.py --check-only

after_success:
  # python --version
  # - if [[ $TRAVIS_BRANCH == "master" ]] && [[ $TRAVIS_PULL_REQUEST == "false" ]]; then
  - if [[ $TRAVIS_PYTHON_VERSION == "3.8" ]]; then
      python -m coveralls;
      python -m codecov;
    fi
  - pkill gunicorn

#jobs:
#  include:
#    - stage: code-coverage
#      python: "3.8"
#      script: |
#        python -m coveralls;
#        python -m codecov;