os: linux
dist: bionic
language: python
python:
  - "3.8"

env:
  HEROKU_REGISTRY_IMAGE: registry.heroku.com/$HEROKU_APP_NAME/web
  DATABASE_TEST_URL: postgresql://postgres@127.0.0.1:5432/users
  FLASK_APP: project/__init__.py
  FLASK_ENV: development
  APP_SETTINGS: project.config.DevelopmentConfig

install:
  - curl https://cli-assets.heroku.com/install-ubuntu.sh | sh

script:
  - echo "OK"