os: linux
dist: bionic
language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
services:
  - postgresql

env:
  DOCKER_COMPOSE_VERSION: 1.25.4
  HEROKU_REGISTRY_IMAGE: registry.heroku.com/$HEROKU_APP_NAME/web
  DATABASE_TEST_USER: postgres
  DATABASE_TEST_PASSWORD: postgres
  DATABASE_TEST_NAME: users
  DATABASE_TEST_HOST: db
  DATABASE_TEST_PORT: 5432
  #DATABASE_TEST_URL: postgresql://$DATABASE_TEST_USER:$DATABASE_TEST_PASSWORD@$DATABASE_TEST_HOST:$DATABASE_TEST_PORT/$DATABASE_TEST_NAME
  DATABASE_TEST_URL: postgresql://postgres@127.0.0.1:5432/users
  FLASK_APP: project/__init__.py
  FLASK_ENV: development
  APP_SETTINGS: project.config.DevelopmentConfig

before_install:
  - python --version

install:
  - pip install -r requirements.txt

before_script:
  #- export FLASK_APP=project/__init__.py
  #- export FLASK_ENV=development
  #- export APP_SETTINGS=project.config.DevelopmentConfig
  #- export DATABASE_TEST_URL=postgresql://postgres@127.0.0.1:5432/users
  - psql -c "CREATE DATABASE users;" -U postgres
  - gunicorn -b 0.0.0.0:5000 manage:app --daemon

script:
  - python -m pytest "project/tests" --cov="project"
  - python -m black project
  - python -m flake8 project
  - python -m isort project/**/*.py --check-only

after_success:
  - python -m coveralls
  - python -m codecov

jobs:
  include:
    - stage: code-coverage
      python: "3.8"
      script: |
        python -m coveralls;
        python -m codecov;