"""empty message

Revision ID: 5856e7e33dc5
Revises: 7d511dc7f14a
Create Date: 2020-04-27 09:31:34.139974

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5856e7e33dc5'
down_revision = '7d511dc7f14a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('remove2', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'remove2')
    # ### end Alembic commands ###
