"""Clen db

Revision ID: 7b93dedee9eb
Revises: 6c481a3fa63d
Create Date: 2020-04-27 18:28:26.236209

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b93dedee9eb'
down_revision = '6c481a3fa63d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'deletenextnext')
    op.drop_column('users', 'deletenext')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('deletenext', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('deletenextnext', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
