"""Add deletenextnext

Revision ID: ea0f987d9c7f
Revises: f515a15e4b51
Create Date: 2020-04-27 18:21:33.546629

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea0f987d9c7f'
down_revision = 'f515a15e4b51'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('deletenextnext', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'deletenextnext')
    # ### end Alembic commands ###
