"""empty message

Revision ID: f515a15e4b51
Revises: 7d511dc7f14a
Create Date: 2020-04-27 17:36:06.648134

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f515a15e4b51'
down_revision = '7d511dc7f14a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('deletenext', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'deletenext')
    # ### end Alembic commands ###
